// 此文件由 oneapi-cli 自动生成，请不要编辑（This file is auto-generated by oneapi-cli, Please do not edit it）
import { PmsProductParam } from "./pmsProductParam";

/**
 * 查询单个商品修改后返回的结果
 * Created by macro on 2018/4/26.
 */
export interface PmsProductResult extends PmsProductParam {
  /** 商品所选分类的父id */
  cateParentId: number;
}
