// 此文件由 oneapi-cli 自动生成，请不要编辑（This file is auto-generated by oneapi-cli, Please do not edit it）
import { PmsProductAttribute } from "../model/pmsProductAttribute";
import { PmsProductAttributeCategory } from "../model/pmsProductAttributeCategory";

/**
 * 带有属性的商品属性分类
 * Created by macro on 2018/5/24.
 */
export interface PmsProductAttributeCategoryItem extends PmsProductAttributeCategory {
  /** 商品属性列表 */
  productAttributeList: Array<PmsProductAttribute>;
}
