// 此文件由 oneapi-cli 自动生成，请不要编辑（This file is auto-generated by oneapi-cli, Please do not edit it）
/**
 * 商品分类对应属性信息
 * Created by macro on 2018/5/23.
 */
export interface ProductAttrInfo {
  /** 商品属性ID */
  attributeId: number;
  /** 商品属性分类ID */
  attributeCategoryId: number;
}
