// 此文件由 oneapi-cli 自动生成，请不要编辑（This file is auto-generated by oneapi-cli, Please do not edit it）
/**
 * 用户登录参数
 * Created by macro on 2018/4/26.
 */
export interface UmsAdminLoginParam {
  /** 用户名 */
  username: string;
  /** 密码 */
  password: string;
}
