// 此文件由 oneapi-cli 自动生成，请不要编辑（This file is auto-generated by oneapi-cli, Please do not edit it）
/**
 * 搜索商品的属性信息
 * Created by macro on 2018/6/27.
 */
export interface EsProductAttributeValue {
  /** */
  id: number;
  /** */
  productAttributeId: number;
  /** */
  value: string;
  /** 属性参数：0->规格；1->参数 */
  type: number;
  /** */
  name: string;
}
