// 此文件由 oneapi-cli 自动生成，请不要编辑（This file is auto-generated by oneapi-cli, Please do not edit it）
/**
 * 会员品牌关注
 * Created by macro on 2018/8/2.
 */
export interface MemberBrandAttention {
  /** */
  id: string;
  /** */
  memberId: number;
  /** */
  memberNickname: string;
  /** */
  memberIcon: string;
  /** */
  brandId: number;
  /** */
  brandName: string;
  /** */
  brandLogo: string;
  /** */
  brandCity: string;
  /** */
  createTime: Date;
}
