// 此文件由 oneapi-cli 自动生成，请不要编辑（This file is auto-generated by oneapi-cli, Please do not edit it）
import request from '@/service/config'
import { CommonResult } from "./model/api/commonResult";
import { CmsSubject } from "./model/model/cmsSubject";
import { CommonPage } from "./model/api/commonPage";

/** 获取全部商品专题 */
export async function listAll() {
  return request<CommonResult<Array<CmsSubject>>>({
    method: 'GET',
    url: '/subject/listAll',
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 根据专题名称分页获取商品专题 */
export async function getList(args: {
    keyword?: string,
    pageNum?: number,
    pageSize?: number,
  }) {
  return request<CommonResult<CommonPage<CmsSubject>>>({
    method: 'GET',
    url: '/subject/list',
    params: {
      keyword: args.keyword,
      pageNum: args.pageNum,
      pageSize: args.pageSize,
    },
    headers: {
      'Content-Type': 'application/json',
    },
  });
}
