// 此文件由 oneapi-cli 自动生成，请不要编辑（This file is auto-generated by oneapi-cli, Please do not edit it）
import request from '@/service/config'
import { CommonResult } from "./model/api/commonResult";
import { HomeContentResult } from "./model/domain/homeContentResult";
import { PmsProduct } from "./model/model/pmsProduct";
import { PmsProductCategory } from "./model/model/pmsProductCategory";
import { CmsSubject } from "./model/model/cmsSubject";

/** 首页内容信息展示 */
export async function content() {
  return request<CommonResult<HomeContentResult>>({
    method: 'GET',
    url: '/home/content',
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 分页获取推荐商品 */
export async function recommendProductList(args: {
    pageSize?: number,
    pageNum?: number,
  }) {
  return request<CommonResult<Array<PmsProduct>>>({
    method: 'GET',
    url: '/home/recommendProductList',
    params: {
      pageSize: args.pageSize,
      pageNum: args.pageNum,
    },
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 获取首页商品分类 */
export async function getProductCateList(args: {
    parentId: number,
  }) {
  return request<CommonResult<Array<PmsProductCategory>>>({
    method: 'GET',
    url: `/home/productCateList/${args.parentId}`,
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 根据分类获取专题 */
export async function getSubjectList(args: {
    cateId?: number,
    pageSize?: number,
    pageNum?: number,
  }) {
  return request<CommonResult<Array<CmsSubject>>>({
    method: 'GET',
    url: '/home/subjectList',
    params: {
      cateId: args.cateId,
      pageSize: args.pageSize,
      pageNum: args.pageNum,
    },
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 分页获取人气推荐商品 */
export async function hotProductList(args: {
    pageNum?: number,
    pageSize?: number,
  }) {
  return request<CommonResult<Array<PmsProduct>>>({
    method: 'GET',
    url: '/home/hotProductList',
    params: {
      pageNum: args.pageNum,
      pageSize: args.pageSize,
    },
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 分页获取新品推荐商品 */
export async function newProductList(args: {
    pageNum?: number,
    pageSize?: number,
  }) {
  return request<CommonResult<Array<PmsProduct>>>({
    method: 'GET',
    url: '/home/newProductList',
    params: {
      pageNum: args.pageNum,
      pageSize: args.pageSize,
    },
    headers: {
      'Content-Type': 'application/json',
    },
  });
}
