// 此文件由 oneapi-cli 自动生成，请不要编辑（This file is auto-generated by oneapi-cli, Please do not edit it）
import request from '../utils/request';
import { MemberReadHistory } from "./model/domain/memberReadHistory";
import { CommonResult } from "./model/api/commonResult";
import { CommonPage } from "./model/api/commonPage";

/** 创建浏览记录 */
export async function create(args: {
    memberReadHistory?: MemberReadHistory,
  }) {
  return request<CommonResult>({
    method: 'POST',
    url: '/member/readHistory/create',
    data: {
      memberReadHistory: args.memberReadHistory,
    },
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 删除浏览记录 */
export async function deleteController(args: {
    ids?: Array<string>,
  }) {
  return request<CommonResult>({
    method: 'POST',
    url: '/member/readHistory/delete',
    data: {
      ids: args.ids,
    },
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 清空浏览记录 */
export async function clear() {
  return request<CommonResult>({
    method: 'POST',
    url: '/member/readHistory/clear',
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 分页获取浏览记录 */
export async function list(args: {
    pageNum?: number,
    pageSize?: number,
  }) {
  return request<CommonResult<CommonPage<MemberReadHistory>>>({
    method: 'GET',
    url: '/member/readHistory/list',
    params: {
      pageNum: args.pageNum,
      pageSize: args.pageSize,
    },
    headers: {
      'Content-Type': 'application/json',
    },
  });
}
