// 此文件由 oneapi-cli 自动生成，请不要编辑（This file is auto-generated by oneapi-cli, Please do not edit it）
import request from '../utils/request';
import { MemberBrandAttention } from "./model/domain/memberBrandAttention";
import { CommonResult } from "./model/api/commonResult";
import { CommonPage } from "./model/api/commonPage";

/** 添加品牌关注 */
export async function add(args: {
    memberBrandAttention?: MemberBrandAttention,
  }) {
  return request<CommonResult>({
    method: 'POST',
    url: '/member/attention/add',
    data: {
      memberBrandAttention: args.memberBrandAttention,
    },
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 取消品牌关注（由于 MemberAttentionController 中 delete 方法名为关键字，此处已自动重命名为 deleteController) */
export async function deleteController(args: {
    brandId?: number,
  }) {
  return request<CommonResult>({
    method: 'POST',
    url: '/member/attention/delete',
    data: {
      brandId: args.brandId,
    },
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 显示当前用户品牌关注列表 */
export async function list(args: {
    pageNum?: number,
    pageSize?: number,
  }) {
  return request<CommonResult<CommonPage<MemberBrandAttention>>>({
    method: 'GET',
    url: '/member/attention/list',
    params: {
      pageNum: args.pageNum,
      pageSize: args.pageSize,
    },
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 显示品牌关注详情 */
export async function detail(args: {
    brandId?: number,
  }) {
  return request<CommonResult<MemberBrandAttention>>({
    method: 'GET',
    url: '/member/attention/detail',
    params: {
      brandId: args.brandId,
    },
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 清空当前用户品牌关注列表 */
export async function clear() {
  return request<CommonResult>({
    method: 'POST',
    url: '/member/attention/clear',
    headers: {
      'Content-Type': 'application/json',
    },
  });
}
