// 此文件由 oneapi-cli 自动生成，请不要编辑（This file is auto-generated by oneapi-cli, Please do not edit it）
import request from '../utils/request';
import { CommonResult } from "./model/api/commonResult";

/** 文件上传 */
export async function upload(args: {
    file?: any,
  }) {
  return request<CommonResult>({
    method: 'POST',
    url: '/minio/upload',
    data: {
      file: args.file,
    },
    headers: {
      'Content-Type': 'multipart/form-data',
    },
  });
}

/** 文件删除（由于 MinioController 中 delete 方法名为关键字，此处已自动重命名为 deleteController) */
export async function deleteController(args: {
    objectName?: string,
  }) {
  return request<CommonResult>({
    method: 'POST',
    url: '/minio/delete',
    params: {
      objectName: args.objectName,
    },
    headers: {
      'Content-Type': 'application/json',
    },
  });
}
