// 此文件由 oneapi-cli 自动生成，请不要编辑（This file is auto-generated by oneapi-cli, Please do not edit it）
import request from '../utils/request';
import { OmsCartItem } from "./model/model/omsCartItem";
import { CommonResult } from "./model/api/commonResult";
import { CartPromotionItem } from "./model/domain/cartPromotionItem";
import { CartProduct } from "./model/domain/cartProduct";

/** 添加商品到购物车 */
export async function add(args: {
    cartItem?: OmsCartItem,
  }) {
  return request<CommonResult>({
    method: 'POST',
    url: '/cart/add',
    data: {
      cartItem: args.cartItem,
    },
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 获取当前会员的购物车列表 */
export async function list() {
  return request<CommonResult<Array<OmsCartItem>>>({
    method: 'GET',
    url: '/cart/list',
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 获取当前会员的购物车列表,包括促销信息 */
export async function listPromotion(args: {
    cartIds?: Array<number>,
  }) {
  return request<CommonResult<Array<CartPromotionItem>>>({
    method: 'GET',
    url: '/cart/list/promotion',
    params: {
      cartIds: args.cartIds,
    },
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 修改购物车中指定商品的数量 */
export async function updateQuantity(args: {
    id?: number,
    quantity?: number,
  }) {
  return request<CommonResult>({
    method: 'GET',
    url: '/cart/update/quantity',
    params: {
      id: args.id,
      quantity: args.quantity,
    },
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 获取购物车中指定商品的规格,用于重选规格 */
export async function getCartProduct(args: {
    productId: number,
  }) {
  return request<CommonResult<CartProduct>>({
    method: 'GET',
    url: `/cart/getProduct/${args.productId}`,
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 修改购物车中商品的规格 */
export async function updateAttr(args: {
    cartItem?: OmsCartItem,
  }) {
  return request<CommonResult>({
    method: 'POST',
    url: '/cart/update/attr',
    data: {
      cartItem: args.cartItem,
    },
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 删除购物车中的指定商品（由于 OmsCartItemController 中 delete 方法名为关键字，此处已自动重命名为 deleteController) */
export async function deleteController(args: {
    ids?: Array<number>,
  }) {
  return request<CommonResult>({
    method: 'POST',
    url: '/cart/delete',
    params: {
      ids: args.ids,
    },
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 清空当前会员的购物车 */
export async function clear() {
  return request<CommonResult>({
    method: 'POST',
    url: '/cart/clear',
    headers: {
      'Content-Type': 'application/json',
    },
  });
}
