// 此文件由 oneapi-cli 自动生成，请不要编辑（This file is auto-generated by oneapi-cli, Please do not edit it）
import request from '../utils/request';
import { OmsOrderReturnReason } from "./model/model/omsOrderReturnReason";
import { CommonResult } from "./model/api/commonResult";
import { CommonPage } from "./model/api/commonPage";

/** 添加退货原因 */
export async function create(args: {
    returnReason?: OmsOrderReturnReason,
  }) {
  return request<CommonResult>({
    method: 'POST',
    url: '/returnReason/create',
    data: {
      returnReason: args.returnReason,
    },
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 修改退货原因 */
export async function update(args: {
    id: number,
    returnReason?: OmsOrderReturnReason,
  }) {
  return request<CommonResult>({
    method: 'POST',
    url: `/returnReason/update/${args.id}`,
    data: {
      returnReason: args.returnReason,
    },
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 批量删除退货原因（由于 OmsOrderReturnReasonController 中 delete 方法名为关键字，此处已自动重命名为 deleteController) */
export async function deleteController(args: {
    ids?: Array<number>,
  }) {
  return request<CommonResult>({
    method: 'POST',
    url: '/returnReason/delete',
    params: {
      ids: args.ids,
    },
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 分页查询退货原因 */
export async function list(args: {
    pageSize?: number,
    pageNum?: number,
  }) {
  return request<CommonResult<CommonPage<OmsOrderReturnReason>>>({
    method: 'GET',
    url: '/returnReason/list',
    params: {
      pageSize: args.pageSize,
      pageNum: args.pageNum,
    },
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 获取单个退货原因详情信息 */
export async function getItem(args: {
    id: number,
  }) {
  return request<CommonResult<OmsOrderReturnReason>>({
    method: 'GET',
    url: `/returnReason/${args.id}`,
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 修改退货原因启用状态 */
export async function updateStatus(args: {
    status?: number,
    ids?: Array<number>,
  }) {
  return request<CommonResult>({
    method: 'POST',
    url: '/returnReason/update/status',
    params: {
      status: args.status,
      ids: args.ids,
    },
    headers: {
      'Content-Type': 'application/json',
    },
  });
}
