// 此文件由 oneapi-cli 自动生成，请不要编辑（This file is auto-generated by oneapi-cli, Please do not edit it）
import request from '../utils/request';
import { CommonResult } from "./model/api/commonResult";
import { OmsOrderSetting } from "./model/model/omsOrderSetting";

/** 获取指定订单设置 */
export async function getItem(args: {
    id: number,
  }) {
  return request<CommonResult<OmsOrderSetting>>({
    method: 'GET',
    url: `/orderSetting/${args.id}`,
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 修改指定订单设置 */
export async function update(args: {
    id: number,
    orderSetting?: OmsOrderSetting,
  }) {
  return request<CommonResult>({
    method: 'POST',
    url: `/orderSetting/update/${args.id}`,
    data: {
      orderSetting: args.orderSetting,
    },
    headers: {
      'Content-Type': 'application/json',
    },
  });
}
