// 此文件由 oneapi-cli 自动生成，请不要编辑（This file is auto-generated by oneapi-cli, Please do not edit it）
import request from '@/service/config'
import { OmsOrderReturnApplyParam } from "./model/domain/omsOrderReturnApplyParam";
import { CommonResult } from "./model/api/commonResult";

/** 申请退货 */
export async function create(args: {
    returnApply?: OmsOrderReturnApplyParam,
  }) {
  return request<CommonResult>({
    method: 'POST',
    url: '/returnApply/create',
    data: {
      returnApply: args.returnApply,
    },
    headers: {
      'Content-Type': 'application/json',
    },
  });
}
