// 此文件由 oneapi-cli 自动生成，请不要编辑（This file is auto-generated by oneapi-cli, Please do not edit it）
import request from '@/service/config'
import { CommonResult } from "./model/api/commonResult";
import { PmsProductAttributeCategory } from "./model/model/pmsProductAttributeCategory";
import { CommonPage } from "./model/api/commonPage";
import { PmsProductAttributeCategoryItem } from "./model/dto/pmsProductAttributeCategoryItem";

/** 添加商品属性分类 */
export async function create(args: {
    name?: string,
  }) {
  return request<CommonResult>({
    method: 'POST',
    url: '/productAttribute/category/create',
    data: {
      name: args.name,
    },
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 修改商品属性分类 */
export async function update(args: {
    id: number,
    name?: string,
  }) {
  return request<CommonResult>({
    method: 'POST',
    url: `/productAttribute/category/update/${args.id}`,
    data: {
      name: args.name,
    },
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 删除单个商品属性分类 */
export async function deleteController(args: {
    id: number,
  }) {
  return request<CommonResult>({
    method: 'GET',
    url: `/productAttribute/category/delete/${args.id}`,
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 获取单个商品属性分类信息 */
export async function getItem(args: {
    id: number,
  }) {
  return request<CommonResult<PmsProductAttributeCategory>>({
    method: 'GET',
    url: `/productAttribute/category/${args.id}`,
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 分页获取所有商品属性分类 */
export async function getList(args: {
    pageSize?: number,
    pageNum?: number,
  }) {
  return request<CommonResult<CommonPage<PmsProductAttributeCategory>>>({
    method: 'GET',
    url: '/productAttribute/category/list',
    params: {
      pageSize: args.pageSize,
      pageNum: args.pageNum,
    },
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 获取所有商品属性分类及其下属性 */
export async function getListWithAttr() {
  return request<CommonResult<Array<PmsProductAttributeCategoryItem>>>({
    method: 'GET',
    url: '/productAttribute/category/list/withAttr',
    headers: {
      'Content-Type': 'application/json',
    },
  });
}
