// 此文件由 oneapi-cli 自动生成，请不要编辑（This file is auto-generated by oneapi-cli, Please do not edit it）
import request from '@/service/config'
import { CommonResult } from "./model/api/commonResult";
import { CommonPage } from "./model/api/commonPage";
import { PmsProduct } from "./model/model/pmsProduct";
import { PmsProductCategoryNode } from "./model/domain/pmsProductCategoryNode";
import { PmsPortalProductDetail } from "./model/domain/pmsPortalProductDetail";

/** 综合搜索、筛选、排序 */
export async function search(args: {
    keyword?: string,
    brandId?: number,
    productCategoryId?: number,
    pageNum?: number,
    pageSize?: number,
    sort?: number,
  }) {
  return request<CommonResult<CommonPage<PmsProduct>>>({
    method: 'GET',
    url: '/product/search',
    params: {
      keyword: args.keyword,
      brandId: args.brandId,
      productCategoryId: args.productCategoryId,
      pageNum: args.pageNum,
      pageSize: args.pageSize,
      sort: args.sort,
    },
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 以树形结构获取所有商品分类 */
export async function categoryTreeList() {
  return request<CommonResult<Array<PmsProductCategoryNode>>>({
    method: 'GET',
    url: '/product/categoryTreeList',
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 获取前台商品详情 */
export async function detail(args: {
    id: number,
  }) {
  return request<CommonResult<PmsPortalProductDetail>>({
    method: 'GET',
    url: `/product/detail/${args.id}`,
    headers: {
      'Content-Type': 'application/json',
    },
  });
}
