// 此文件由 oneapi-cli 自动生成，请不要编辑（This file is auto-generated by oneapi-cli, Please do not edit it）
import request from '@/service/config'
import { CommonResult } from "./model/api/commonResult";
import { PmsSkuStock } from "./model/model/pmsSkuStock";

/** 根据商品ID及sku编码模糊搜索sku库存 */
export async function getList(args: {
    pid: number,
    keyword?: string,
  }) {
  return request<CommonResult<Array<PmsSkuStock>>>({
    method: 'GET',
    url: `/sku/${args.pid}`,
    params: {
      keyword: args.keyword,
    },
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 批量更新sku库存信息 */
export async function update(args: {
    pid: number,
    skuStockList?: Array<PmsSkuStock>,
  }) {
  return request<CommonResult>({
    method: 'POST',
    url: `/sku/update/${args.pid}`,
    data: {
      skuStockList: args.skuStockList,
    },
    headers: {
      'Content-Type': 'application/json',
    },
  });
}
