// 此文件由 oneapi-cli 自动生成，请不要编辑（This file is auto-generated by oneapi-cli, Please do not edit it）
import request from '../utils/request';
import { SmsFlashPromotion } from "./model/model/smsFlashPromotion";
import { CommonResult } from "./model/api/commonResult";

/** 添加活动 */
export async function create(args: {
    flashPromotion?: SmsFlashPromotion,
  }) {
  return request<CommonResult>({
    method: 'POST',
    url: '/flash/create',
    data: {
      flashPromotion: args.flashPromotion,
    },
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 编辑活动（由于 SmsFlashPromotionController 中 update 方法存在多个 url，此处已自动重命名为 updateWithHash31E59F) */
export async function updateWithHash31E59F(args: {
    id: number,
    flashPromotion?: SmsFlashPromotion,
  }) {
  return request<any>({
    method: 'POST',
    url: `/flash/update/${args.id}`,
    data: {
      flashPromotion: args.flashPromotion,
    },
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 删除活动（由于 SmsFlashPromotionController 中 delete 方法名为关键字，此处已自动重命名为 deleteController) */
export async function deleteController(args: {
    id: number,
  }) {
  return request<any>({
    method: 'POST',
    url: `/flash/delete/${args.id}`,
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 修改上下线状态（由于 SmsFlashPromotionController 中 update 方法存在多个 url，此处已自动重命名为 updateWithHash193D97) */
export async function updateWithHash193D97(args: {
    id: number,
    status?: number,
  }) {
  return request<any>({
    method: 'POST',
    url: `/flash/update/status/${args.id}`,
    data: {
      status: args.status,
    },
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 获取活动详情（由于 SmsFlashPromotionController 中 getItem 方法存在多个 url，此处已自动重命名为 getItemWithHashF82349) */
export async function getItemWithHashF82349(args: {
    id: number,
  }) {
  return request<any>({
    method: 'GET',
    url: `/flash/${args.id}`,
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 根据活动名称分页查询（由于 SmsFlashPromotionController 中 getItem 方法存在多个 url，此处已自动重命名为 getItemWithHash42E8E6) */
export async function getItemWithHash42E8E6(args: {
    keyword?: string,
    pageSize?: number,
    pageNum?: number,
  }) {
  return request<any>({
    method: 'GET',
    url: '/flash/list',
    params: {
      keyword: args.keyword,
      pageSize: args.pageSize,
      pageNum: args.pageNum,
    },
    headers: {
      'Content-Type': 'application/json',
    },
  });
}
