// 此文件由 oneapi-cli 自动生成，请不要编辑（This file is auto-generated by oneapi-cli, Please do not edit it）
import request from '@/service/config'
import { CommonResult } from "./model/api/commonResult";
import { UmsMemberLevel } from "./model/model/umsMemberLevel";

/** 查询所有会员等级 */
export async function list(args: {
    defaultStatus?: number,
  }) {
  return request<CommonResult<Array<UmsMemberLevel>>>({
    method: 'GET',
    url: '/memberLevel/list',
    params: {
      defaultStatus: args.defaultStatus,
    },
    headers: {
      'Content-Type': 'application/json',
    },
  });
}
