// 此文件由 oneapi-cli 自动生成，请不要编辑（This file is auto-generated by oneapi-cli, Please do not edit it）
import request from '@/service/config'
import { CommonResult } from "./model/api/commonResult";
import { UmsResourceCategory } from "./model/model/umsResourceCategory";

/** 查询所有后台资源分类 */
export async function listAll() {
  return request<CommonResult<Array<UmsResourceCategory>>>({
    method: 'GET',
    url: '/resourceCategory/listAll',
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 添加后台资源分类 */
export async function create(args: {
    umsResourceCategory?: UmsResourceCategory,
  }) {
  return request<CommonResult>({
    method: 'POST',
    url: '/resourceCategory/create',
    data: {
      umsResourceCategory: args.umsResourceCategory,
    },
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 修改后台资源分类 */
export async function update(args: {
    id: number,
    umsResourceCategory?: UmsResourceCategory,
  }) {
  return request<CommonResult>({
    method: 'POST',
    url: `/resourceCategory/update/${args.id}`,
    data: {
      umsResourceCategory: args.umsResourceCategory,
    },
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 根据ID删除后台资源 */
export async function deleteController(args: {
    id: number,
  }) {
  return request<CommonResult>({
    method: 'POST',
    url: `/resourceCategory/delete/${args.id}`,
    headers: {
      'Content-Type': 'application/json',
    },
  });
}
