// 此文件由 oneapi-cli 自动生成，请不要编辑（This file is auto-generated by oneapi-cli, Please do not edit it）
import request from '../utils/request';
import { UmsResource } from "./model/model/umsResource";
import { CommonResult } from "./model/api/commonResult";
import { CommonPage } from "./model/api/commonPage";

/** 添加后台资源 */
export async function create(args: {
    umsResource?: UmsResource,
  }) {
  return request<CommonResult>({
    method: 'POST',
    url: '/resource/create',
    data: {
      umsResource: args.umsResource,
    },
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 修改后台资源 */
export async function update(args: {
    id: number,
    umsResource?: UmsResource,
  }) {
  return request<CommonResult>({
    method: 'POST',
    url: `/resource/update/${args.id}`,
    data: {
      umsResource: args.umsResource,
    },
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 根据ID获取资源详情 */
export async function getItem(args: {
    id: number,
  }) {
  return request<CommonResult<UmsResource>>({
    method: 'GET',
    url: `/resource/${args.id}`,
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 根据ID删除后台资源 */
export async function deleteController(args: {
    id: number,
  }) {
  return request<CommonResult>({
    method: 'POST',
    url: `/resource/delete/${args.id}`,
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 分页模糊查询后台资源 */
export async function list(args: {
    categoryId?: number,
    nameKeyword?: string,
    urlKeyword?: string,
    pageSize?: number,
    pageNum?: number,
  }) {
  return request<CommonResult<CommonPage<UmsResource>>>({
    method: 'GET',
    url: '/resource/list',
    params: {
      categoryId: args.categoryId,
      nameKeyword: args.nameKeyword,
      urlKeyword: args.urlKeyword,
      pageSize: args.pageSize,
      pageNum: args.pageNum,
    },
    headers: {
      'Content-Type': 'application/json',
    },
  });
}

/** 查询所有后台资源 */
export async function listAll() {
  return request<CommonResult<Array<UmsResource>>>({
    method: 'GET',
    url: '/resource/listAll',
    headers: {
      'Content-Type': 'application/json',
    },
  });
}
