// 此文件由 oneapi-cli 自动生成，请不要编辑（This file is auto-generated by oneapi-cli, Please do not edit it）
/** */
export interface CmsSubjectProductRelation {
  /** */
  id: number;
  /** */
  subjectId: number;
  /** */
  productId: number;
}
