// 此文件由 oneapi-cli 自动生成，请不要编辑（This file is auto-generated by oneapi-cli, Please do not edit it）
/** */
export interface PmsMemberPrice {
  /** */
  id: number;
  /** */
  productId: number;
  /** */
  memberLevelId: number;
  /** 会员价格 */
  memberPrice: number;
  /** */
  memberLevelName: string;
}
