// 此文件由 oneapi-cli 自动生成，请不要编辑（This file is auto-generated by oneapi-cli, Please do not edit it）
/** */
export interface PmsProductAttributeCategory {
  /** */
  id: number;
  /** */
  name: string;
  /** 属性数量 */
  attributeCount: number;
  /** 参数数量 */
  paramCount: number;
}
