// 此文件由 oneapi-cli 自动生成，请不要编辑（This file is auto-generated by oneapi-cli, Please do not edit it）
/** */
export interface PmsProductAttributeValue {
  /** */
  id: number;
  /** */
  productId: number;
  /** */
  productAttributeId: number;
  /** 手动添加规格或参数的值，参数单值，规格有多个时以逗号隔开 */
  value: string;
}
