// 此文件由 oneapi-cli 自动生成，请不要编辑（This file is auto-generated by oneapi-cli, Please do not edit it）
/** */
export interface PmsProductLadder {
  /** */
  id: number;
  /** */
  productId: number;
  /** 满足的商品数量 */
  count: number;
  /** 折扣 */
  discount: number;
  /** 折后价格 */
  price: number;
}
