// 此文件由 oneapi-cli 自动生成，请不要编辑（This file is auto-generated by oneapi-cli, Please do not edit it）
/** */
export interface SmsCouponProductRelation {
  /** */
  id: number;
  /** */
  couponId: number;
  /** */
  productId: number;
  /** 商品名称 */
  productName: string;
  /** 商品编码 */
  productSn: string;
}
