// 此文件由 oneapi-cli 自动生成，请不要编辑（This file is auto-generated by oneapi-cli, Please do not edit it）
/** */
export interface SmsCouponProductCategoryRelation {
  /** */
  id: number;
  /** */
  couponId: number;
  /** */
  productCategoryId: number;
  /** 产品分类名称 */
  productCategoryName: string;
  /** 父分类名称 */
  parentCategoryName: string;
}
