// 此文件由 oneapi-cli 自动生成，请不要编辑（This file is auto-generated by oneapi-cli, Please do not edit it）
/** */
export interface UmsResourceCategory {
  /** */
  id: number;
  /** 创建时间 */
  createTime: Date;
  /** 分类名称 */
  name: string;
  /** 排序 */
  sort: number;
}
