// 此文件由 oneapi-cli 自动生成，请不要编辑（This file is auto-generated by oneapi-cli, Please do not edit it）
/**
 * 通用返回对象
 * Created by macro on 2019/4/19.
 */
export interface CommonResult<T = any> {
  /** 状态码 */
  code: number;
  /** 提示信息 */
  message: string;
  /** 数据封装 */
  data: T;
}
